name: Deploy TAG to Prd
run-name: Deploy tag ${{ github.ref_name }} to Prd

on:
  workflow_dispatch:
    inputs:
      jira_ticket:
          description: 'JIRA ticket number'
          required: false
          default: ''

jobs:
  deploy_api:
    uses: esgi-corp/mulesoft_cicd/.github/workflows/api_deploy.yaml@main
    with:
      env: prd
      branch: ${{ github.ref_name }}
      jira_ticket: ${{ github.event.inputs.jira_ticket }}
      workers: ${{ vars.WORKERS }}
      vcores: ${{ vars.VCORES }} 
      app_name: "sapi-weather-app"
      repo_props_name: "mulesoft-sapi-weather-properties"
    secrets: inherit