name: Deploy TAG to Dev
run-name: Deploy tag ${{ github.ref_name }} to Dev

on:
  workflow_dispatch:

jobs:
  deploy_api:
    uses: esgi-corp/mulesoft_cicd/.github/workflows/api_deploy.yaml@main
    with:
      env: dev
      branch: ${{ github.ref_name }}
      workers: ${{ vars.WORKERS }}
      vcores: ${{ vars.VCORES }} 
      app_name: "sapi-weather-app"
      repo_props_name: "mulesoft-sapi-weather-properties"
    secrets: inherit