name: Deploy branch to Sandbox
run-name: Deploy branch ${{ github.event.inputs.branch }} to Sandbox

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      jira_ticket:
        description: 'Jira ticket number'
        required: false
        default: ''

jobs:
  deploy_api:
    uses: esgi-corp/mulesoft_cicd/.github/workflows/api_deploy.yaml@main
    with:
      env: sandbox
      branch: ${{ github.event.inputs.branch }}
      jira_ticket: ${{ github.event.inputs.jira_ticket }}
      workers: ${{ vars.WORKERS }}
      vcores: ${{ vars.VCORES }} 
      app_name: "sapi-weather-app"
      repo_props_name: "mulesoft-sapi-weather-properties"
    secrets: inherit
